###  CREATE A NEW COMMENT 

POST http://localhost:3000/comments/BUG_1
Content-Type: application/json

{
	"comment":"Novo asdfasdfadsf",
	"author":"carvalho.ie18@gmail.com"
}

### GET COMMENTS BY ISSUE	 

GET http://localhost:3000/comments/BUG_1

### GET A SPECIFIC COMMENT BY ISSUE AND COMMENT ID	

GET http://localhost:3000/comments/BUG_1/5f978c14eec4f3955eb8690b

