### GET ALL ISSUES (WITH COMMENTS)
GET http://localhost:3000/issues

### GET INDIVIDUAL ISSUES

GET http://localhost:3000/issues/BOOK_1


###  ADD A NEW ISSUE TO A PROJECT INDIVIDUALLY

POST http://localhost:3000/issues/BOOK
Content-Type: application/json

{	
	"text": "SeconD Issue on BOOK Project",
	"description": "Exception 123456",
	"status": "Open"
}

###  UPDATED THE STATUS OF AN ISSUE

PATCH  http://localhost:3000/issues/BOOK_1
Content-Type: application/json

{	
	"status": "Open"
}






### GET ALL ISSUES FOR A PROJECT

GET http://localhost:3000/issues/projects/BOOK
