GET http://localhost:3000/projects

### FIND A PROJECT BY ID

GET http://localhost:3000/projects/5f9405c2165543cf3028305f

    
### CREATE A NEW PROJECT

POST http://localhost:3000/projects/
Content-Type: application/json

{
    "slug": "BUG",
	"name": "BUG SOFTWARE MANAGEMENT",
	"descripion": "This project will help me to record all bugs I come across and then use it to learn more about programming laguange"
}


### UPDATE A PROJECT BY ID

PATCH  http://localhost:3000/projects/5f9405c2165543cf3028305f
Content-Type: application/json

{
    "slug": "BUG",
	"name": "BUG SOFTWARE MANAGEMENT",
	"descripion": "This project will help me to record all bugs I come across and then use it to learn more about programming laguange"
}

### DELET A PROJECT BY ID

DELETE http://localhost:3000/projects/5f940f6fdeb01482e7cf825f