//GET ALL PROJECTS
GET http://localhost:3000/projects

### GET INDIVIDUAL PROJECTS
GET http://localhost:3000/projects/BOOK

### ADD A NEW PROJECT INDIVIDUALLY
POST http://localhost:3000/projects/
Content-Type: application/json

{
    "slug": "HOTEL",
	"name": "BOOK SOFTWARE MANAGEMENT BUG",
	"description": "Control the chaos around solving software bugs. Quickly diagnose problems in your codebase, enjoy faster development cycles and make sure users are having error free experiences."
}


### UPDATE A PROJECT BY ID (SLUG)
PATCH  http://localhost:3000/projects/BOOK
Content-Type: application/json
// It is not possible to change the slug because it must be unique

{
   "name": "BOOK SOFTWARE MANAGEMENT BUG THE BEST",
   "description": "Control the chaos around solving software bugs. Quickly diagnose problems in your codebase, enjoy faster development cycles and make sure users are having error free experiences."
}

