//GET ALL PROJECTS
GET http://localhost:3000/projects



### GET INDIVIDUAL PROJECTS
GET http://localhost:3000/projects/BOOK

    
### ADD A NEW PROJECT INDIVIDUALLY
POST http://localhost:3000/projects/
Content-Type: application/json

{
    "slug": "BUG",
	"name": "BUG SOFTWARE MANAGEMENT BUG",
	"descripion": "This project will help me to record all bugs I come across and then use it to learn more about programming laguange"
}


### UPDATE A PROJECT BY ID
PATCH  http://localhost:3000/projects/BUG
Content-Type: application/json
// It is not possible to change the slug because it must be unic

{
    "name": "BUssssG BEST SOFTWARE MANAGEMENT",
	"descripion": " project will help me to record all bugs I come across and then use it to learn more about programming laguange"
}

