### GET ALL USERS
GET http://localhost:3000/users

### GET AN USER INDIVIDUALLY BY EMAIL

GET http://localhost:3000/users/daniela@gmail.com

    
### ADD NEW USER INDIVIDUALLY

POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Adalberto",
    "email": "adalberto@gmail.com",
    "userType": "admin",
    "key": "123456"
}

### UPDATE A USER 

PATCH  http://localhost:3000/users/5f946ab4fa595a9bebfe54cc
Content-Type: application/json

{
    "name": "David",
    "email": "david@gmail.com",
    "userType": "admin@gmail.com"
}