### GET ALL USERS
GET http://localhost:3000/users

### GET AN USER INDIVIDUALLY BY EMAIL

GET http://localhost:3000/users/daniela@gmail.com

    
### ADD NEW USER INDIVIDUALLY

POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Gilberto",
    "email": "gilberto@gmail.com",
    "userType": "Admin",
    "key": "852369"
}

### UPDATE A USER 

PATCH  http://localhost:3000/users/gilberto@gmail.com
Content-Type: application/json

{
    "name": "Gilberto",
    "userType": "Admin",
    "key": "741258"
}